### ISSUE TITLE
Semaphore in ISR

### ISSUE THREAD

**Issue by macdroid53** [claudeheintz/LXESP32DMX#18]
I note in the FreeRTOS documentation it states that the xSemaphoreTake() should never be used in an ISR.

Is there a caveat to that since the ISR in example inputTest.ino has a call to that in the second line?

`
void receiveCallback(int slots) {
	if ( slots ) {
	    xSemaphoreTake( ESP32DMX.lxDataLock, portMAX_DELAY );`

**Comment by claudeheintz** [comment]
Good question.  The semaphore seems to work to coordinate between the ISR and the main task.  The alternate would be to use some other signal that could be used to avoid a partial or corrupted read by the receiving task (not the ISR task).  That was an issue before the semaphore was added.
