### ISSUE TITLE
DPORT_SET_PERI_REG_MASK and DPORT_CLEAR_PERI_REG_MASK missing

### ISSUE THREAD

**Issue by sajingeo** [claudeheintz/LXESP32DMX#2]
Archiving built core (caching) in: /var/folders/d5/8kb4x7k91nb8hxgf2q0ly6tr0000gp/T/arduino_cache_991257/core/core_espressif_esp32_esp32thing_FlashFreq_80,UploadSpeed_921600_9fad3c1318533d50fa964562bb12526c.a
arduino.ar(esp32-hal-uart.c.o):(.literal.uartBegin+0x10): undefined reference to `DPORT_SET_PERI_REG_MASK'
arduino.ar(esp32-hal-uart.c.o):(.literal.uartBegin+0x14): undefined reference to `DPORT_CLEAR_PERI_REG_MASK'
arduino.ar(esp32-hal-uart.c.o): In function `uartBegin':
/Users/sxg08/Documents/Arduino/hardware/espressif/esp32/cores/esp32/esp32-hal-uart.c:414: undefined reference to `DPORT_SET_PERI_REG_MASK'
/Users/sxg08/Documents/Arduino/hardware/espressif/esp32/cores/esp32/esp32-hal-uart.c:414: undefined reference to `DPORT_SET_PERI_REG_MASK'
/Users/sxg08/Documents/Arduino/hardware/espressif/esp32/cores/esp32/esp32-hal-uart.c:414: undefined reference to `DPORT_SET_PERI_REG_MASK'
/Users/sxg08/Documents/Arduino/hardware/espressif/esp32/cores/esp32/esp32-hal-uart.c:414: undefined reference to `DPORT_CLEAR_PERI_REG_MASK'
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board SparkFun ESP32 Thing.

**Comment by claudeheintz** [comment]
This compiles without a problem using the latest espressif ESP32 Arduino from GitHub.  (compiled for ESP Dev Module)  Is there a particular board that causes this issue?  Or, is it the version of ESP32 Arduino core that you have in Arduino/hardware/espressif ?
