### ISSUE TITLE
Latest Espressif core 2.02

### ISSUE THREAD

**Issue by midikidi** [claudeheintz/LXESP32DMX#30]
Trying to build LXESP32DMX with latest core 2.0.2 as it fixes a lot of interrupt issues
getting compile errors with replacement uart code in extras
attempted to mere break detection SLIP mod into latest lib
cant find ISR receive handler any help please

**Comment by claudeheintz** [comment]
There is now an experimental branch named w202 that is-compatible-with/requires v 2.0.2 of the SDK provided by Arduino Boards Manager

**Comment by claudeheintz** [comment]
the w202 branch is now the main branch
